feature/ make popups
lomaya-baryery-admin/main pull request #35
Opened 2022-11-08 19:45 UTC by BobrikAU

2022-11-09 17:19 UTC, NikolaySmolov requested changes
Саша, привет!
Здорово стилизовал, чувствуется подход с душой, здорово что комментируешь - помогает быстрее разобраться! Круто что помимо обертки модального окна сделал еще два компонента!
Мои концептуальные предложения:
- Сделать два компонента для модального окна как в бургере: Modal и ScreenOverlay. Так будет легче стилизовать и вешать слушателей событий. Остальное что уже есть сделать отдельными компонентами и унести в components
- Все что мы хотим показать в модальном окне должно попасть в него через проп children. Проект может развиваться и могу появляться еще какие-то компоненты, которые должны быть в модалке.
- Модальное окно должно монтироваться в ReactPortal
- У модального окна не должно быть состояния показывать его или нет, потому что модальное окно должно размонтироваться чтобы слушатель эскейпа удалился (сейчас он остается, можешь проверить через console.log)

2022-11-09 17:19 UTC, NikolaySmolov commented on src/ui/popup/popup.tsx
> +  const externalPopupClass = externalClassName || '';
я поставил круту библиотеку - classnames она позволяет творить чудеса с именами классов и даже байндиться к стилям.
`import classnames from 'classnames/bind'
const cn = classnames.bind(styles)`
но лучше использовать без bind из
`import cn from 'classnames'`

2022-11-09 17:19 UTC, NikolaySmolov commented on src/ui/popup/popup.tsx
> +    if (overlayRef.current) overlayRef.current.addEventListener('click', clickOverlay);
onClick лучше повесить элемент плюс сейчас модалка закрывается если будешь выделять текст внутри и отпустишь кнопку мыши на оверлее - это не очень хорошо и этого можно избежать.

2022-11-09 17:19 UTC, NikolaySmolov commented on src/ui/popup/popup.tsx
> +                    `${styles.overlay} ${styles.popup_visibility_false}`}
рендер должен быть в React портале

2022-11-09 17:19 UTC, NikolaySmolov commented on src/ui/popup/popup.tsx
> +          <CloseIcon
В интерфейсе с которыми можно взаимодействовать пользователь ожидает смену стрелки на лапку. Иконка тоже принимает стили )

2022-11-10 17:16 UTC, BobrikAU commented on src/ui/popup/popup.tsx
> +    if (overlayRef.current) overlayRef.current.addEventListener('click', clickOverlay);
Проблема "модалка закрывается если будешь выделять текст внутри и отпустишь кнопку мыши на оверлее" решена

2022-11-10 18:15 UTC, BobrikAU commented on src/ui/popup/popup.tsx
> +  const externalPopupClass = externalClassName || '';
Использовано

2022-11-10 18:21 UTC, BobrikAU commented on src/ui/popup/popup.tsx
> +          <CloseIcon
Исправлено. Чего то я тупанул здесь. Хотя ведь думал, что мышь должны реагировать на наведение

2022-11-10 18:38 UTC, BobrikAU commented on src/ui/popup/popup.tsx
> +                    `${styles.overlay} ${styles.popup_visibility_false}`}
Исправлено

2022-11-10 21:45 UTC, BobrikAU commented on src/ui/popup/popup.tsx
> +    if (overlayRef.current) overlayRef.current.addEventListener('click', clickOverlay);
использован onMouseDown

2022-11-14 15:13 UTC, NikolaySmolov approved these changes
Саша, привет!
Все здорово!
Посмотри плиз на неиспользуемые переменные в импортах - они есть.
Тебе для инфо, в сторис transition настроен на 400ms, для такого элемента как модалка это долго, обычно диапазон 150 - 250 ms ну максимум 300, так пользователь не будет ощущать будто интерфейс тормозит.

Можешь влить после правок без ревью.

2022-11-14 15:13 UTC, niksmo commented on src/ui/popup/popup.tsx
> +    const modalRoot = document.getElementById('modal-root');
- поиск можно вынести наружу функции, чтобы каждый раз не искать элемент в DOM дереве.
- в html не добавлен div с этим id

2022-11-15 13:12 UTC, closed without merging